// https://projecteuler.net/problem=2

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

let results = 0;

function fibonacciSum(first = 1, second = 2, limit = 4000000) {
  const nextNumber = first + second;

  if (nextNumber <= limit) {
    if (nextNumber % 2 === 0) {
      results += nextNumber;
    }

    fibonacciSum(second, nextNumber, limit);
  }
}

fibonacciSum()

console.log(results);
